base_url = "https://bossenti.dev"    # Domain name of your website
title = "bossenti"            # Title of your website
description = "Welcome to my blog! Dive into data & software engineering, cloud technologies, and the open source ecosystem."
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feeds = true                # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["rss.xml"]         # The file name of feed, "feed.xml" / "atom.xml" / "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
    { name = "blog", path = "/posts", is_external = false },
    { name = "datahub", path = "/datahub", is_external = false },
    { name = "talks", path = "/talks", is_external = false },
    { name = "about", path = "/about", is_external = false },
]
blog_section_path = "/posts"

force_theme = false
back_link_text = "Back"

footer_copyright = "© 2025 bossenti"
footer_credits = true

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false
reaction_align = "right"
reaction_endpoint = "https://example.com/api/reaction"
